### ISSUE TITLE
iOSでのデバッグ

### ISSUE THREAD

**Issue by nagisa-laughcraft** [snm-project-team/snm-app#5]
create-react-native-appを使っているので、
エミュレータの環境等整えればmacでデバッグ出来るはず

macと実機（私は持ってないので方法検討）でデバッグが出来て、wikiに手順を書いたらクローズ

**Comment by to4-yanagi** [comment]
権限周りのためにシミュレータが自動で立ち上がらない？

https://github.com/react-community/create-react-native-app/issues/647

**Comment by nagisa-laughcraft** [comment]
npm run iosが出来ない問題があったが、
とりあえずアプリを再度構築したら解決、また発生したらissue立てる
